# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Test branch

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
jobs:
  test:

    runs-on: ubuntu-latest
    container: gradle:jdk17-focal

    permissions: write-all

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: set up gradlew for execution
      run: |
        chmod +x gradlew

    - name: Copy overlays to support testing
      run: |
        ./gradlew copyAllOverlays


    - name: run gradle build
      run: |
        ./gradlew construct:liquidbtools:build

